name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Sombody101/global-build/.github/actions/global-build@main
        with:
          bin_name: 'rgecko'
      - uses: softprops/action-gh-release@v2
        with:
          files: rgecko-*